#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --job-name=pidm_environment_setup
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=05:00:00
#SBATCH --mem=32000M
#SBATCH --output=jobs/outputs/pidm_env_setup_%A.out
#SBATCH --error=jobs/outputs/pidm_env_setup_%A_error.out

module purge
module load 2022
module load Anaconda3/2022.05

# create the conda environment
conda env create -f modules/PIDM/pose_environment.yml

echo "Conda environment created successfully!"
